name: docs
on: # shows that it willl trigger on a push to main branch
push:
branches:
- main # make sure this isn't master

jobs:
docs:  # the only one job being executed
name: Docs
runs-on: ubuntu-latest
steps: # the steps that will be done if run

- uses: actions/checkout@v2

- name: Install Python
uses: actions/setup-python@v1
with:
    python-version: 3.8

- name: Install requirements
run: |
    pip3 install sphinx-rtd-theme

- name: Build docs 
run: | # the commands we are running
    cd docs
    make html

# https://github.com/peaceiris/actions-gh-pages
- name: Deploy
if: success()
uses: peaceiris/actions-gh-pages@v3
with:
    publish_branch: gh-pages
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: docs/_build/html/
